### ISSUE TITLE
deps versions

### ISSUE THREAD

**Issue by joeblew99** [kkeuning/goa-react#1]
I am playing with this, but getting a fair bit of dependency breaks, which is understandable considering that goa is moving fast.

How do you feel about versioning the dependencies ?

**Comment by kkeuning** [comment]
Would be happy to improve that.  Can you provide some specifics about what is breaking?

**Comment by kkeuning** [comment]
Updated examples with versioning and confirmed dependencies.  See README.md for detailed instructions.  These examples now currently target goa tag v1.0.0 and my forks of other examples referred to in the slides.
